apiVersion: v1
kind: PersistentVolume
metadata:
  name: checkmk-pv-storage
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast
  local:
    path: /omd/sites
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-worker
          - master-worker1
          - master-worker2
